// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	AccountType string  `json:"accountType"`
	Number      int     `json:"number"`
	Agency      int     `json:"agency"`
	Holder      *Holder `json:"holder"`
}

type Holder struct {
	Name     string  `json:"name"`
	LastName *string `json:"lastName,omitempty"`
}

type NewAccount struct {
	AccountType string     `json:"accountType"`
	Number      int        `json:"number"`
	Agency      int        `json:"agency"`
	Holder      *NewHolder `json:"holder"`
}

type NewHolder struct {
	Name     string  `json:"name"`
	LastName *string `json:"lastName,omitempty"`
}

type NewPixKey struct {
	PixKeyType string      `json:"pixKeyType"`
	PixKey     string      `json:"pixKey"`
	Account    *NewAccount `json:"account"`
}

type PixKey struct {
	ID         string   `json:"id"`
	PixKeyType string   `json:"pixKeyType"`
	PixKey     string   `json:"pixKey"`
	Account    *Account `json:"account"`
}
