// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPixKey struct {
	PixKeyType     string  `json:"pixKeyType"`
	PixKey         string  `json:"pixKey"`
	AccountType    string  `json:"accountType"`
	AccountNumber  int     `json:"accountNumber"`
	AgencyNumber   int     `json:"agencyNumber"`
	HolderName     string  `json:"holderName"`
	HolderLastName *string `json:"holderLastName,omitempty"`
}

type PixKey struct {
	ID             string  `json:"id"`
	PixKeyType     string  `json:"pixKeyType"`
	PixKey         string  `json:"pixKey"`
	AccountType    string  `json:"accountType"`
	AccountNumber  int     `json:"accountNumber"`
	AgencyNumber   int     `json:"agencyNumber"`
	HolderName     string  `json:"holderName"`
	HolderLastName *string `json:"holderLastName,omitempty"`
}
